on: push


jobs:
  package:
    runs-on: windows-2019
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x

    - name: Chechout
      uses: actions/checkout@v2

    - name: Install Wails
      run: go get github.com/wailsapp/wails/cmd/wails@v1.9.1

    - name: Build for windows
      run: |
        New-Item -ItemType directory -Path "$HOME\.wails" -Force
        Copy-Item -Path "$PWD\wails.json" -Destination "$HOME\.wails\wails.json"
        choco install mingw
        wails build -f -p
        Compress-Archive -Path "$PWD\build\wombat.exe" -DestinationPath "$PWD\Wombat_Windows_x86_64.zip"

    - name: Upload windows zip
      uses: actions/upload-artifact@v2
      with:
        name: Wombat_Windows_x86_64.zip
        path: Wombat_Windows_x86_64.zip
    



